### ISSUE TITLE
Delete unverified users

### ISSUE THREAD

**Issue by nightsailor** [flozender/BuildIT#134]
Problem: Delete the user accounts that are not verified after an hour of its creation.

Possible approach:

- Create an admin panel page with

  - An input form that takes time in hour's and deletes all unverified accounts that were created before that time.

  - A table similar to manageusers, add an additional column 'after created' with format `HH:MM`
( Time between account created and now ).

- Write/Test the backend api for the same.

**Comment by nightsailor** [comment]
@noobguy77 Can you take this up?

**Comment by noobguy77** [comment]
I will check it out.
