### ISSUE TITLE
Delete contests from admin panel

### ISSUE THREAD

**Issue by flozender** [flozender/BuildIT#95]
We need the following tasks to be carried out:

- [ ] Create frontend page with dropdown and delete CTA
- [ ] Create/edit backend delete contest API
- [ ] Test delete API
- [ ] Link frontend to backend

**Comment by flozender** [comment]
@talha8045 Can you take this up?

**Comment by talha8045** [comment]
I will try and make it.

**Comment by flozender** [comment]
I've handled the task.
